### ISSUE TITLE
raidable

### ISSUE THREAD

**Issue by isoz** [PocketEssential/UltraFaction#16]
Is Deaths until raidable working? Can't seem to find the event for that.

**Comment by xZeroMCPE** [comment]
No, not yet.

**Comment by isoz** [comment]
What's the ideal method for raiding then?

**Comment by xZeroMCPE** [comment]
The claim system has not even been implemented yet, as of now, it's just simple raiding, no protection at all. Will start pushing to UltraFaction with those implemented soon.
